env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - docs
    - test
    - Merge pull request
    - Merge branch
    - goreleaser
brew:
  github:
    owner: liamawhite
    name: homebrew-licenser
  folder: Formula
  homepage:  https://github.com/liamawhite/licenser
  description: Verify and append licenses to your GitHub repositories
  test: |
    system "#{bin}/licenser -v"
